### ISSUE TITLE
Баги

### ISSUE THREAD

**Issue by yuchiko** [KudriaIvan/site-jwood#1]
- добавить фиксированное меню, без повторений на каждой секции
- телефон и почту в Контактах сделать кликабельными
- убрать странную анимацию при наведении на scroll down
- сделать scroll down кликабельным
- добавить плавность при hover галлереи
- мы говорили про 100vh для главного экрана, где ?
- ссылки в меню должны плавно скроллить на определенные секции сайта
- почистить от закомментированых областей
- alt всюду заполнить, href не оставлять пустым

**Comment by KudriaIvan** [comment]
изменил меню
телефон и почту сделал кликабельными <a href="tel:+44 212 432 444" class="footer-content__info">+44 212 432 444</a>
Анимацию переделал, поменял внешний вид ссылки
Скролл теперь переносит с задержкой до нужного блока   $('#scrollToAbout').click( function(){ 
	var scroll_el = $(this).attr('href');
        if ($(scroll_el).length != 0) { 
	    $('html, body').animate({ scrollTop: $(scroll_el).offset().top }, 1200); 
        }
	    return false;
    });
Сделал плавность в галлереи 
Велком блок 100вх
Скролл сделал 
Почистил код и заполнил alt
